module HMem.DB.Schema
  ( -- * Workspaces
    WorkspaceT(..)
  , workspaceSchema

    -- * Observations
  , ObservationT(..)
  , observationSchema

    -- * Projects
  , ProjectT(..)
  , projectSchema

    -- * Tasks
  , TaskT(..)
  , taskSchema

    -- * Task dependencies
  , TaskDependencyT(..)
  , taskDependencySchema

    -- * Workspace groups
  , WorkspaceGroupT(..)
  , workspaceGroupSchema
  , WorkspaceGroupMemberT(..)
  , workspaceGroupMemberSchema

    -- * Saved views
  , SavedViewT(..)
  , savedViewSchema
  , activeSavedView

  , activeWorkspace
  , activeProject
  , activeTask
  , deletedNow

    -- * PostgreSQL full-text search types
  , PgTSVector(..)
  , PgTSQuery(..)
  , PgRegConfig(..)
  ) where

import Data.Aeson (Value)
import Data.ByteString (ByteString)
import Data.Int (Int16)
import Data.Text (Text)
import Data.Time (UTCTime)
import Data.UUID (UUID)
import GHC.Generics (Generic)
import Rel8

import HMem.Types (ProjectStatus, TaskStatus, SubjectKind, WorkspaceType)

------------------------------------------------------------------------
-- PostgreSQL full-text search types (opaque wrappers for Rel8)
------------------------------------------------------------------------

-- | Phantom type representing PostgreSQL @tsvector@.
-- Uses ByteString internally because PostgreSQL’s binary wire protocol
-- sends tsvector in a non-UTF-8 format.  We never inspect the Haskell
-- value — it is only used at the SQL expression level.
newtype PgTSVector = PgTSVector ByteString

instance DBType PgTSVector where
  typeInformation = case mapTypeInformation PgTSVector (\(PgTSVector bs) -> bs) (typeInformation :: TypeInformation ByteString) of
    TypeInformation enc dec delim _ ->
      TypeInformation enc dec delim (TypeName (QualifiedName "tsvector" Nothing) [] 0)

-- | Phantom type representing PostgreSQL @tsquery@.
newtype PgTSQuery = PgTSQuery Text

instance DBType PgTSQuery where
  typeInformation = case mapTypeInformation PgTSQuery (\(PgTSQuery t) -> t) (typeInformation :: TypeInformation Text) of
    TypeInformation enc dec delim _ ->
      TypeInformation enc dec delim (TypeName (QualifiedName "tsquery" Nothing) [] 0)

-- | Phantom type representing PostgreSQL @regconfig@.
newtype PgRegConfig = PgRegConfig Text

instance DBType PgRegConfig where
  typeInformation = case mapTypeInformation PgRegConfig (\(PgRegConfig t) -> t) (typeInformation :: TypeInformation Text) of
    TypeInformation enc dec delim _ ->
      TypeInformation enc dec delim (TypeName (QualifiedName "regconfig" Nothing) [] 0)

------------------------------------------------------------------------
-- Workspaces
------------------------------------------------------------------------

-- NOTE [unsafeDefault]:  Throughout the DB modules, @unsafeDefault@ from
-- Rel8 is used in INSERT expressions for columns whose values are
-- generated by PostgreSQL at write time — UUIDs (@gen_random_uuid()@),
-- timestamps (@now()@), tsvectors (trigger-maintained), and status
-- enums with column defaults.  The function is "unsafe" only in the
-- Rel8 sense that the expression bypasses Haskell type-checking of the
-- DEFAULT value; the actual defaults are defined in the SQL schema and
-- are always safe.

data WorkspaceT f = WorkspaceT
  { wsId        :: Column f UUID
  , wsName      :: Column f Text
  , wsType      :: Column f WorkspaceType
  , wsGhOwner   :: Column f (Maybe Text)
  , wsGhRepo    :: Column f (Maybe Text)
  , wsDeletedAt :: Column f (Maybe UTCTime)
  , wsCreatedAt :: Column f UTCTime
  , wsUpdatedAt :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

workspaceSchema :: TableSchema (WorkspaceT Name)
workspaceSchema = TableSchema
  { name    = "workspaces"
  , columns = WorkspaceT
      { wsId        = "id"
      , wsName      = "name"
      , wsType      = "workspace_type"
      , wsGhOwner   = "gh_owner"
      , wsGhRepo    = "gh_repo"
        , wsDeletedAt = "deleted_at"
      , wsCreatedAt = "created_at"
      , wsUpdatedAt = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Observations
------------------------------------------------------------------------

-- The conditionally provisioned pgvector @embedding@ column is intentionally
-- absent here.  Keeping the mandatory Rel8 shape portable lets all base
-- operations work when pgvector is not installed.
data ObservationT f = ObservationT
  { obsId          :: Column f UUID
  , obsWorkspaceId :: Column f UUID
  , obsSubjectKind :: Column f SubjectKind
  , obsSubject     :: Column f Text
  , obsGitSha      :: Column f Text
  , obsContent     :: Column f Text
  , obsSearchVector :: Column f PgTSVector
  , obsCreatedAt   :: Column f UTCTime
  , obsUpdatedAt   :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

observationSchema :: TableSchema (ObservationT Name)
observationSchema = TableSchema
  { name = "observations"
  , columns = ObservationT
      { obsId           = "id"
      , obsWorkspaceId  = "workspace_id"
      , obsSubjectKind  = "subject_kind"
      , obsSubject      = "subject"
      , obsGitSha       = "git_sha"
      , obsContent      = "content"
      , obsSearchVector = "search_vector"
      , obsCreatedAt    = "created_at"
      , obsUpdatedAt    = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Projects
------------------------------------------------------------------------

data ProjectT f = ProjectT
  { projId           :: Column f UUID
  , projWorkspaceId  :: Column f UUID
  , projParentId     :: Column f (Maybe UUID)
  , projName         :: Column f Text
  , projDescription  :: Column f (Maybe Text)
  , projStatus       :: Column f ProjectStatus
  , projPriority     :: Column f Int16
  , projMetadata     :: Column f Value
  , projSearchVector :: Column f PgTSVector
  , projDeletedAt    :: Column f (Maybe UTCTime)
  , projCreatedAt    :: Column f UTCTime
  , projUpdatedAt    :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

projectSchema :: TableSchema (ProjectT Name)
projectSchema = TableSchema
  { name    = "projects"
  , columns = ProjectT
      { projId           = "id"
      , projWorkspaceId  = "workspace_id"
      , projParentId     = "parent_id"
      , projName         = "name"
      , projDescription  = "description"
      , projStatus       = "status"
      , projPriority     = "priority"
      , projMetadata     = "metadata"
      , projSearchVector = "search_vector"
      , projDeletedAt    = "deleted_at"
      , projCreatedAt    = "created_at"
      , projUpdatedAt    = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Tasks
------------------------------------------------------------------------

data TaskT f = TaskT
  { taskId           :: Column f UUID
  , taskWorkspaceId  :: Column f UUID
  , taskProjectId    :: Column f (Maybe UUID)
  , taskParentId     :: Column f (Maybe UUID)
  , taskTitle        :: Column f Text
  , taskDescription  :: Column f (Maybe Text)
  , taskStatus       :: Column f TaskStatus
  , taskPriority     :: Column f Int16
  , taskMetadata     :: Column f Value
  , taskDueAt        :: Column f (Maybe UTCTime)
  , taskCompletedAt  :: Column f (Maybe UTCTime)
  , taskSearchVector :: Column f PgTSVector
  , taskDeletedAt    :: Column f (Maybe UTCTime)
  , taskCreatedAt    :: Column f UTCTime
  , taskUpdatedAt    :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

taskSchema :: TableSchema (TaskT Name)
taskSchema = TableSchema
  { name    = "tasks"
  , columns = TaskT
      { taskId           = "id"
      , taskWorkspaceId  = "workspace_id"
      , taskProjectId    = "project_id"
      , taskParentId     = "parent_id"
      , taskTitle        = "title"
      , taskDescription  = "description"
      , taskStatus       = "status"
      , taskPriority     = "priority"
      , taskMetadata     = "metadata"
      , taskDueAt        = "due_at"
      , taskCompletedAt  = "completed_at"
      , taskSearchVector = "search_vector"
      , taskDeletedAt    = "deleted_at"
      , taskCreatedAt    = "created_at"
      , taskUpdatedAt    = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Task dependencies
------------------------------------------------------------------------

data TaskDependencyT f = TaskDependencyT
  { tdTaskId      :: Column f UUID
  , tdDependsOnId :: Column f UUID
  } deriving stock Generic
    deriving anyclass Rel8able

taskDependencySchema :: TableSchema (TaskDependencyT Name)
taskDependencySchema = TableSchema
  { name    = "task_dependencies"
  , columns = TaskDependencyT
      { tdTaskId      = "task_id"
      , tdDependsOnId = "depends_on_id"
      }
  }

------------------------------------------------------------------------
-- Workspace groups
------------------------------------------------------------------------

data WorkspaceGroupT f = WorkspaceGroupT
  { wgId          :: Column f UUID
  , wgName        :: Column f Text
  , wgDescription :: Column f (Maybe Text)
  , wgCreatedAt   :: Column f UTCTime
  , wgUpdatedAt   :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

workspaceGroupSchema :: TableSchema (WorkspaceGroupT Name)
workspaceGroupSchema = TableSchema
  { name    = "workspace_groups"
  , columns = WorkspaceGroupT
      { wgId          = "id"
      , wgName        = "name"
      , wgDescription = "description"
      , wgCreatedAt   = "created_at"
      , wgUpdatedAt   = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Workspace group members
------------------------------------------------------------------------

data WorkspaceGroupMemberT f = WorkspaceGroupMemberT
  { wgmGroupId     :: Column f UUID
  , wgmWorkspaceId :: Column f UUID
  , wgmJoinedAt    :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

workspaceGroupMemberSchema :: TableSchema (WorkspaceGroupMemberT Name)
workspaceGroupMemberSchema = TableSchema
  { name    = "workspace_group_members"
  , columns = WorkspaceGroupMemberT
      { wgmGroupId     = "group_id"
      , wgmWorkspaceId = "workspace_id"
      , wgmJoinedAt    = "joined_at"
      }
  }

------------------------------------------------------------------------
-- Saved views
------------------------------------------------------------------------

data SavedViewT f = SavedViewT
  { svId          :: Column f UUID
  , svWorkspaceId :: Column f UUID
  , svName        :: Column f Text
  , svDescription :: Column f (Maybe Text)
  , svEntityType  :: Column f Text
  , svQueryParams :: Column f Value
  , svDeletedAt   :: Column f (Maybe UTCTime)
  , svCreatedAt   :: Column f UTCTime
  , svUpdatedAt   :: Column f UTCTime
  } deriving stock Generic
    deriving anyclass Rel8able

savedViewSchema :: TableSchema (SavedViewT Name)
savedViewSchema = TableSchema
  { name    = "saved_views"
  , columns = SavedViewT
      { svId          = "id"
      , svWorkspaceId = "workspace_id"
      , svName        = "name"
      , svDescription = "description"
      , svEntityType  = "entity_type"
      , svQueryParams = "query_params"
      , svDeletedAt   = "deleted_at"
      , svCreatedAt   = "created_at"
      , svUpdatedAt   = "updated_at"
      }
  }

------------------------------------------------------------------------
-- Soft-delete helpers
------------------------------------------------------------------------

activeWorkspace :: WorkspaceT Expr -> Expr Bool
activeWorkspace row = isNull row.wsDeletedAt

activeProject :: ProjectT Expr -> Expr Bool
activeProject row = isNull row.projDeletedAt

activeTask :: TaskT Expr -> Expr Bool
activeTask row = isNull row.taskDeletedAt

activeSavedView :: SavedViewT Expr -> Expr Bool
activeSavedView row = isNull row.svDeletedAt

deletedNow :: Expr (Maybe UTCTime)
deletedNow = unsafeLiteral "now()"
